# Site settings
title: Jonathan Mercer
email: mercer.jon+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi. I'm Jon Mercer, UBC student, software developer, and videographer. My current home base is Vancouver.
  I'm still learning Jekyll, so this blog is still under construction.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonmercer
github_username:  jonmercer

# Build settings
markdown: kramdown
